#!/bin/bash

names=`cut -f1 -d, $1 | sort | uniq`

for name in $names
do
    if [ $name == "Seller" ]
    then
        continue
    else
        grep "^Seller," $1 > $name.csv
        grep "^$name," $1 >> $name.csv
    fi
done
